AWSTemplateFormatVersion: '2010-09-09'
Resources:
  App:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudfront-course.s3.eu-central-1.amazonaws.com/start.yml
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        IPV6Enabled: true
        HttpVersion: http2
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /
        DefaultCacheBehavior:
          Compress: true
          TargetOriginId: frontend
          DefaultTTL: 0
          MinTTL: 0
          MaxTTL: 0
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          ViewerProtocolPolicy: "redirect-to-https"
        CacheBehaviors:
          - PathPattern: /api/tags
            TargetOriginId: api
            ViewerProtocolPolicy: https-only
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            Compress: true
            DefaultTTL: 60
            MinTTL: 60
            MaxTTL: 60
            ForwardedValues:
              Cookies:
                Forward: none
              QueryString: true
          - PathPattern: /api/articles
            TargetOriginId: api
            ViewerProtocolPolicy: https-only
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            Compress: true
            DefaultTTL: 60
            MinTTL: 60
            MaxTTL: 60
            ForwardedValues:
              Cookies:
                Forward: none
              QueryString: true
          - PathPattern: /api/*
            TargetOriginId: api
            ViewerProtocolPolicy: https-only
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            Compress: true
            DefaultTTL: 0
            MinTTL: 0
            MaxTTL: 0
            ForwardedValues:
              Cookies:
                Forward: all
              QueryString: true
              Headers:
                - '*'
          - PathPattern: /static/*
            TargetOriginId: frontend
            ViewerProtocolPolicy: https-only
            Compress: true
            DefaultTTL: 31536000
            MinTTL: 31536000
            MaxTTL: 31536000
            ForwardedValues:
              Cookies:
                Forward: none
              QueryString: false
        Origins:
          - Id: frontend
            DomainName: !GetAtt App.Outputs.FrontendHost
            CustomOriginConfig:
              HTTPPort: 80
              OriginProtocolPolicy: http-only
          - Id: api
            DomainName: !GetAtt App.Outputs.BackendHost
            CustomOriginConfig:
              HTTPPort: !GetAtt App.Outputs.BackendPort
              OriginProtocolPolicy: http-only
Outputs:
  CloudFrontURL:
    Value: !GetAtt Distribution.DomainName
